---
title: "Rewiring food webs via trophic rewilding"
author: ""
date: ""
header-includes:
   - \usepackage{geometry}
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
bibliography: main.bib
csl: apa.csl
geometry: margin=3cm
---

Emilio Berti$^{1, 2, *}$, Scott Jarvie$^{1, 2}$, and Jens-Christian Svenning$^{1, 2}$

$^1$ Section for Ecoinformatics and Biodiversity, Department of Bioscience, Aarhus University, Ny Munkegade 114, DK-8000 Aarhus C, Denmark.

$^2$ Center for Biodiversity Dynamics in a Changing World (BIOCHANGE), Department of Bioscience, Aarhus University, Ny Munkegade 114, DK-8000 Aarhus C, Denmark.

$^{*}$ corresponding author: emilio.berti@bios.au.dk

Keywords: Food webs - Human-driven extinctions - Mammals - Megafauna - Rewilding - Trophic interactions.

\clearpage

# Abstract
During the late-Quaternary, humans triggered mass extinctions of vertebrates, with a selective size-bias towards large mammals, causing losses of top-down trophic processes in ecosystems. Trophic rewilding, the (re)introduction of species to promote self-sustaining biodiverse ecosystems, has been proposed as a strategy to restore ecosystem trophic complexity. Yet, the extent of restoration possible via trophic rewilding is poorly understood. Using combined current species distributions and present-natural ranges, counter-factual maps of where mammals would live today without anthropogenic influences, we modelled climatic suitability of terrestrial mammals and simulated a rewilding scenario where extinct species are replaced by phylogentically-related functional analogues. We then inferred food webs in protected areas >= 5,000 km^2 as well as geographically-unbiased random areas to investigate the effects of late-Quaternary extinctions on ecosystems’ trophic structure and potential recoveries through rewilding. Our results show that trophic complexity and top-down control in terrestrial ecosystems have been severely degraded by human activities. We also found that trophic rewilding can rewire food webs, partially restoring lost predator-prey interactions and ecosystem trophic structure. Under the rewilding selection criteria, however, ecosystems remained depleted of higher trophic levels and of top-down trophic interactions with small to large differences compared to natural conditions. Overall... **I fell we need a broader conclusion sentence here.**

# Introduction
Humans have degraded ecosystems worldwide, removing from the environment species, their interactions, and the ecological processes associated with them [@dirzo2014defaunation; @valiente2015beyond]. Human-driven extirpations of mammals date back to at least the Late Pleistocene, with a large bodied size-selectivity causing extinctions of over half of megafauna genera (121 out of 196 genera >= 44 kg have gone extinct @barnosky2008megafauna; @smith2018body). As Late Pleistocene mammal extinctions acutely affected large body-sized species, interactions previously maintained by pre-human biodiverse megafauna communities have been removed from ecological networks [@gill2014ecological; @malhi2016megafauna]. This extinctions have modified ecosystem processes and functions, e.g. extirpations of apex predators have reduced control of prey densities, and generated trophic cascades that altered ecosystems trophic structure and dynamics [@estes2011trophic; @ripple2014status].

Trophic rewilding, the (re)introduction of species to promote self-sustaining biodiverse ecosystems [@svenning2016science], has been proposed to re-establish lost ecological interactions [@perino2019rewilding]. For example, the reintroduction of wolves into Yellowstone National Park restored and top-down control and predation pressure, re-establishing trophic cascades [@beschta2016riparian]. Rewilding is not universally accepted, however, with criticism on both its conceptual and ecological validity [@nogues2016rewilding; @hayward2019reintroducing]. Empirical data from rewilding projects are scarce, limited in time, and geographically biased [@tanentzap2018unintentional], and community responses to rewilding can be contradictory and inconclusive, arising the issue of when and how to rewild [@alston2019reciprocity]. Despite increasing evidence for the restoration potential of rewilding from local studies [@perino2019rewilding], there is limited knowledge of the potential of rewilding to rewire ecological networks to pre-human conditions at a global scale.

Macroecological approaches provide an appropriate framework to assess the potential of rewilding to rewire ecological networks at large scales with deep-time perspectives [@zhang2018trophic; @mendoza2019climate]. These approaches can highlight similarities between extinct and extant species and suggest suitable ecological replacements for rewilding [@pires2017rewilding]. Moreover, inference of biotic interactions and reconstruction of prehistoric ecological networks can be used to examine the consequences of human-driven extinctions and extirpations of large mammals [@yeakel2014collapse; @pires2015pleistocene; @marjakangas2018estimating]. By combining a rewilding scenario supported by paleoecological data with macroecologically-grounded reconstructions of interaction networks, it is possible to infer rewilding communities and interactions and examine the potential of rewilding to rewire ecological networks to pre-human conditions [@pires2017rewilding].

![Conceptual representation of rewiring food webs via trophic rewilding. A) The protected areas and counter-factual areas >= 5,000 km^2 included, with colours representing the six biogeographic realms considered in the study. We excluded Antarctica because it did not have any terrestrial mammal and Oceania as it did not have any suitable protected area. B) Network representation of food webs. In the network, species are nodes and predator-prey interactions are edges. The Late Pleistocene human-driven extinctions removed species and trophic interactions (red nodes and edges). Rewilding aims to restore lost interactions by replacing extinct species with suitable ecological analogues (green nodes) that can rewire food webs establishing functionally analogue links (green edges).](Figures/conceptual.png)

In this study, we investigate the potential of rewilding to rewire terrestrial mammal food webs in large (>=5,000 km^2) protected areas and geographically-unbiased random areas at global scale (Fig. 1). We infer food webs for three scenarios: 1) present-natural, i.e. a counter-factual scenario where mammals have not been influenced by human activities through time [@faurby2015historic; @faurby2018phylacine]; 2) current conditions; and 3) a rewilding scenario where extant species can re-expand to present-natural ranges and extinct species can be replaced by closely-related, similarly-sized functional analogues that tolerate comparable climates. We then compare the food webs for the three scenarios to investigate how much current food webs are depleted of predator-prey interactions and whether rewilding can rewire food webs to present-natural states.

# Materials and methods
## Overview
Expanding the terminology of @genes2017credit, we quantified: a) current debt, the number of species and interactions lost because of past extinctions; b) rewilding credit, the number of lost species and interactions restored under the rewilding scenario; and c) rewilding deficit, the degree of past losses that cannot be restored via rewilding. By comparing current debt, rewilding credit, and rewilding deficit, we assessed whether rewilding credit can balance current debt and assessed the remaining rewilding deficit.

We quantified current debt, rewilding credit, and rewilding deficit in large (>= 5,000 km^2) protected areas (n = 209) with strict International Union for Conservation of Nature (IUCN) management categories (Ia, Ib, and II). Rewilding is more feasible in large, strictly managed protected areas and human-wildlife coexistence less problematic. Because large protected areas are concentrated in areas with low biodiversity [@daru2019spatial], we examined rewilding restoration potential also random areas >= 5,000 km^2 (n = 206) randomly scattered within each biogeographic realm (Figure 1) to investigate the potential of a global rewilding scenario without geographic biases.

Our methodology was divided into three modelling steps. First, we ran correlative species distribution models (SDMs) to identify climatically suitable habitat for terrestrial mammals. Second, we selected for each extinct species a closely related, similarly-sized functional analogue following conservative selection criteria. Third, we reconstructed species geographic distribution and inferred food webs under present-natural, current, and rewilding scenarios. By contrasting food web for the three scenarios, we investigated whether rewilding can restore current defaunated food webs to present-natural conditions. We ran analyses for protected and random areas separately; in the following sections we describe in details the methods used for protected areas, implying that the same was done for the random areas where applicable.

## Species distribution models
Correlative SDMs are currently the main tools used to derive spatially explicit predictions of environmental suitability for species [@elith2009species]. They typically achieve this through identification of statistical relationships between species observations and environmental descriptors [@guisan2005predicting]. To overcome biases introduced by anthropogenic pressures on where terrestrial mammals live in building SDMs [@jarvie2018using], we used current and present-natural range maps from the PHYLACINE database [@faurby2018phylacine]. Current ranges were generated from the IUCN range polygon maps for current, natural, and reintroduced ranges only [@iucn2016iucn]. Present-natural ranges are estimates of where species could be today in the complete absence of influence of modern humans (*Homo sapiens*) through time [@faurby2018phylacine] and can be viewed as pre-human ranges adjusted for present-day climate [@faurby2015historic]. The present-natural ranges combine knowledge of species' current IUCN range with historic distributions, fossil co-occurrence data, and range modifications caused by humans [@faurby2015historic].

We generated presence locations within combined current and present-natural range maps with a 20 km separation distance, excluding locations reported above the highest elevation for each species in the IUCN Red List or, if not stated, 4,000 meters, which is roughly the 95 percentile for upper elevations of mammals [@iucn2016iucn]. Elevation was determined for presence locations using the EarthEnv-DEM90 digital elevation model [@robinson2014earthenv]. In total, we identified 4,206 extant terrestrial mammal species with range maps.

As environmental predictors for the SDMs, we used four climatic variables from the Worldclim database at 2.5 arc-minute resolution [@fick2017worldclim]: maximum temperature of the warmest month, minimum temperature of the coldest month, precipitation of wettest quarter, and precipitation of driest quarter. We selected these variables as they capture extreme conditions and, thus, likely represent factors limiting the distributions of terrestrial mammals. We ensured that the variance inflation factor among climatic variables was below 4 to minimize potential issues with multi-collinearity. Climate layers were reprojected using bilinear interpolation to a $5 km^2$ resolution with a Behrmann equal-area projection, which was used in all downstream analyses. To model the climatic suitability of terrestrial mammals, we fitted maximum entropy (Maxent) models as implemented in the recently released *maxnet* R-package [@phillips2017opening]. Maxent is a presence-background approach, in which environments occupied by a species are contrasted with the available environmental space [@elith2011statistical; @merow2013practical]. For the background areas, we calculated species-specific buffers around the combined current and present-natural ranges to reflect the dispersal abilities of each species, obtained as the maximum edge-centroid distance of the largest continuous range [@poo2014galictis; @hof2018bioenergy] (see electronic supplementary material, figure S1).

We excluded 76 species with restricted ranges from modelling distributions as they had less than 10 presence points. In total, we modelled 4,130 of the 4,206 living terrestrial mammals. Predictive performance and model overfitting were assessed through five-fold cross validation. To assess quality of SDMs, we also compared predicted suitable ranges with introduced range maps from @iucn2016iucn and @lundgren2018introduced, which were not used to train Maxent models (Appendix).

## Selection of rewilding candidates
We simulated a rewilding scenario where extant terrestrial mammals re-expanded to occupy their present-natural ranges and extinct species are replaced by living mammals following conservative selection criteria. We searched for rewilding candidates that were phylogenetically close and functionally similar to globally extinct species and that could tolerate climatic conditions of their ranges. Population restorations, i.e. reintroductions into present-natural ranges, were prioritised over introductions of functional analogues, as moving species’ outside their indigenous range is inherently riskier than reintroductions due to unforeseeable uncertainties and ecological risks (**Fernández et al. 2017**). We assessed rewilding replacements separately for each biogeographic realm [@olson2001terrestrial], areas where ecological and evolutionary processes operate most strongly [@olson2002global]. We excluded Antarctica because no terrestrial mammal lives there and Oceania because no strictly managed IUCN protected areas >= 5,000 km^2 are found there (Figure 1).

For each globally extinct species, we selected as rewilding replacements the species from the same family that had similar size (within the 50% range of extinct species' body mass) and the largest climatically suitable range within the present-natural of the extinct species in each biogeographic realm. We made two exceptions to the above criteria: 1) because proboscidean species >= 1,000 kg have analogous ecological and functional roles [@janzen1982neotropical; @donlan2005re; @josh2006pleistocene], the two extant elephants *Elephas maximus* and *Loxodonta africana* were allowed to replace, where climatically suitable, all megaherbivores (>= 1,000 kg; @malhi2016megafauna) of the order Proboscidea. 2) Because Felidae and Ursidae megacarnivores (>= 100 kg; @malhi2016megafauna) regulate the abundance and activity of large herbivores that are smaller than megaherbivores [@laundre2010landscape; @ripple2014status], necessary to restore trophic complexity in self-sustaining ecosystems [@perino2019rewilding], extant Felidae and Ursidae megacarnivores were allowed to replace extinct species within their families.

To avoid possible negative impacts of introducing functional analogues into the present-natural ranges of similarly-sized - within 50\% of the body mass - extant species of the same taxonomic group, we excluded introductions of rewilding candidates if their proposed ranges overlapped with the ranges of reintroduced species. This was done to limit the risk of displacing extant native species through competition [@linnell2000interference]. If we identified more than one rewilding candidate, we selected the species that had the largest climatically suitable range overlapping with the present-natural range of the extinct species in each biogeographic realm. We did not select species for rewilding that violated any of the above criteria. See electronic supplement material, figure S\# for a schematic representation of the selection criteria.

<!-- **to SI**
Our analyses also constrained rewilding to:
1) within the present-natural range of extinct terrestrial mammals of the same family using the taxonomy in @faurby2018phylacine, with an exception to the order level for _Proboscidea_. This is because extant elephants (*Elephas maximus* and *Loxodonta africana*) are frequently considered as ecological replacements for extinct members of this group [@donlan2005re; @josh2006pleistocene], due to their phenotypic similarity (large body size, body shape, tusks, trunk) and being a keystone species as megaherbivores [@owen1987pleistocene], similar to extinct *Elephantidae*, *Gomphotheriidae*, *Mammutidae* and *Stegodontidae* [@janzen1982neotropical].
2) Within 50% of the body mass range of extinct terrestrial mammals in the same family with exceptions for the order *Proboscidea*, and families *Felidae* and *Ursidae*. The exception for extant elephants was that if species were not found within 50% of the body mass of extinct *Proboscidea* >= 1,000 kg the mass range was extended to include Proboscideans with mass >= 1000 kg because, because, as noted above, elephants play critical roles in ecosystems, similar to other large extinct Proboscideans [@janzen1982neotropical; @josh2006pleistocene] + (**Barlow 2000**). The exception for *Felidae* and *Ursidae* is that if extant species in each family were not found within 50% of the body mass of extinct species >= 100 kg within the family the mass range was extended to any species with mass >= 100 kg. This is because megacarnivores (>= 100 kg; @malhi2016megafauna), play an integral part of a complete animal community by influencing ecosystems through regulating the abundance and activity of large herbivores that are smaller than megaherbivores, either through direct predation or by behavioural changes induced by 'landscapes of fear' [@laundre2010landscape; @ford2014large; @ripple2014status; @atkins2019cascading].  -->

## Reconstructing food webs
We reconstructed mammal assemblages within 209 large terrestrial protected areas (>= 5,000 km^2; Fig. 1), selected from the World Database of Protected Area (@WDPA, downloaded June 2019). Following previous global studies [@runge2015protected; @jones2018one], we excluded protected areas without detailed geographic information, proposed and designated sites not considered protected areas internationally, sites with an unknown status, UNESCO Biosphere Reserves, and marine-only sites as well as the marine portion of coastal sites. As large areas with limited human use facilitate the establishment of self-sustaining population of large mammals [@woodroffe1998edge; @chundawat2016size], we kept only protected areas with strict IUCN management category (Ia, Ib, and II) and total surface >= 5,000 km^2 after dissolving adjacent geometries together. Because the protected area network poorly overlap with current biodiversity hotspots [@daru2019spatial], we investigated the effects of human activities and the restoration potential of rewilding also in 209 counter-factual areas randomly distributed within each biogeographic realm (Figure 1). For each area but 3 counter-factual areas without terrestrial mammals, we obtained the mammal assemblage under present-natural scenario using the PHYLACINE present-natural range maps (including extinct species) and for current conditions using the current ranges. Rewilding assemblages were estimated from combined current, reintroduction (present-natural including only extant species), and rewilding ranges obtained using SDMs and selection of the best functional analogues for extinct species.

To infer food webs for each area, we combined phylogenetic inference with a trait-based approach [@pomeranz2019inferring]. Phylogeny has been shown to be a good predictor of trophic interactions [@eklof2011relevance], as closely related species share similar resources [@gray2015joining]. We performed phylogenetic inference at the family level, a reasonable trade-off between accuracy of predictions and data availability [@gray2015joining]. We gathered  predator-prey interaction data from the ECOWeB database [@cohen2010ecoweb], the Global Biotic Interactions (GLOBI) database [@poelen2014global], and two published food webs [@baskerville2011spatial; @de2011serengeti]. Each observed interaction between a prey and a predator was assigned to all species of the respective families. We then used a trait-based approach to remove interactions inferred using phylogeny that were not supported by macroecological evidence [@pomeranz2019inferring]. This trait-based approach uses the relationship between the body mass of prey and predators, which structures trophic interactions in food webs [@williams2000simple; @owen2008predator; @segura2016exceptional]. Following previous studies [@gravel2013inferring; @pomeranz2019inferring], we used the range within the 10% and the 90% regression quantiles to obtain dietary niches of carnivores, i.e. the body mass range of their prey. Phylogenetically inferred predator-prey interactions outside the dietary niche were removed from the food web.

After food webs were inferred, we assigned species to trophic levels defined by diet and body mass, reflecting the trophic and ecological role of species [@malhi2016megafauna]. For carnivores, we divided them into three trophic levels: i) megacarnivores >= 100 kg, which are generally apex predators and dominate food webs; ii) large carnivores 21.5 - 99 kg, which can predate on large prey and are subjected to top-down control from megacarnivores; and iii) small carnivores < 21.5 kg, which can predate only on smaller prey [@carbone1999energetic]. For herbivores, we also used three trophic levels: i) megaherbivores >= 1,000 kg, which are mostly free from predation; ii) large herbivores 45 - 999 kg, which are predated only by large carnivores and megacarnivores; and iii) small herbivores < 45 kg, which are predated by all carnivores trophic levels [@hopcraft2010herbivores].

## Statistical analyses
For the three food web scenarios, we calculated the number of species present in each trophic level and the number of predator-prey interactions connecting trophic levels. We then compared the number of species in each trophic level between present-natural and current conditions to estimate current trophic richness debt and between current and rewilding scenarios to assess rewilding trophic richness credit. We also compared the number of trophic interactions across trophic levels between present-natural and current scenarios to obtain the current interaction debt and between current and rewilding scenarios to quantify rewilding interaction credit. Moreover, we compared the difference in the number of species per trophic level and the number of interactions between trophic levels under present-natural and rewilding scenarios to quantify rewilding deficit, i.e. the amount of current debts that cannot be balanced by rewilding credit.

To estimate significance and magnitude of differences among the scenarios, we used generalised linear mixed models (GLMMs). We selected the error distribution for the GLMMs based on the response data type and to remedy overdispersion [@zuur2009mixed]. We used a Poisson distribution to model the number of species at each trophic level with the fixed effects scenario, trophic level, and their interaction. A negative binomial distribution was used to model the predator-prey interactions across trophic levels with the fixed effects scenario, trophic levels involved in the link, and their interaction. For both GLMMs, we used the random effects area identity to account for **non-comparable pseudoreplicates** and biogeographic realms because of their different ecological histories. We assessed significance among scenarios by performing pair-wise contrasts with Bonferroni correction and estimated the magnitude of the differences using Cohen's *d* effect size: [@cohen1988statistical; @sawilowsky2009new]. Protected and counter-factual areas were analysed and are separately.

All data processing and analyses were performed in the R programming language version 3.6.1 [@R] using packages tidyverse [@wickham2019welcome], maxnet [@maxnet], dismo [@dismo], sf [@sf], raster [@raster], doParallel [@doParallel], foreach [@foreach], quantreg [@quantreg], performance [@performance], emmeans [@emmeans], and estimate [@estimate]. All spatial analyses were conducted using the Behrmann cylindrical equal-area projection. Biogeographic realms were derived using the shapefile from the World Wildlife Foundation ([WWF](https://www.worldwildlife.org/publications/terrestrial-ecoregions-of-the-world), @olson2002global). Figures were made using packages ggplot2 [@ggplot2] with maps displayed in the Molleweide projection.

# Results
Predictive performance of SDMs was on average very high to excellent, while model overfitting was generally low (electronic supplementary material, Table S1 and figure S2). The projected climatic suitability ranges captured much of the known introduction ranges of species obtained from @lundgren2018introduced and @iucn2016iucn (figure S2). These results indicate the SDMs give reliable projections of climatic suitability of terrestrial mammals.

Due to our conservative rewilding selection criteria, we found no replacements for 15 globally extinct families (electronic supplementary material). <!-- _Archaeolemuridae_, _Chaeropodidae_, _Diprotodontidae_, _Macrauchenidae_, _Megaladapidae_, _Megatheriidae_, _Mylodontidae_, _Nesophontidae_, _Nothrotheridae_, _Palaeopropithecidae_, _Prolagidae_, _Proterotheriidae_, _Thylacinidae_, _Thylacoleonidae_, and _Toxodontidae_. --> In total, we identified 94 living species that could be used as functional analogues for 127 out of 334 extinct terrestrial mammals of 34 families (electronic supplementary material, Table S3).

In the protected areas >= 5,000 km^2, we found a lower number of species in trophic levels under current conditions than in the present-natural scenario except for small herbivores and small carnivores (Table 1, figure 1). The largest decrease in number of species were for megacarnivores, megaherbivores, and large herbivores, with large (*d* >= 0.80) or very large (*d* >= 1.20) differences. Small carnivores and small herbivores were not significantly affected by extinctions. Under the rewilding scenario, the number of megacarnivores, megaherbivores, and large herbivores significantly increased from current conditions, with small or medium effect sizes. For large carnivores, however, the number of species did not increase significantly with rewilding. The number of species for the trophic levels megacarnivores, megaherbivores, large carnivores, and large herbivores remained smaller than the present-natural. In the large counter-factual areas we observed similar but more pronounced patterns than in protected areas (figure 2).

Table 1: Differences between regression coefficients estimates from generalised linear mixed models for the number of species per trophic level among the present-natural, current, and rewilding scenarios. The differences were obtained using multiple pair-wise contrasts accounting for variation across biogeographic realms and food webs. Superscripts show the *p*-value of the contrasts adjusted with Bonferroni correction and subscripts show the magnitude of the effect size of the change using Cohen's *d*: very small, *d* < 0.20; small *d* = 0.20-0.49; medium *d* = 0.50-0.79; large, *d* = 0.80-1.20; very large, *d* = 1.20-2.00; and huge, *d* >= 2.00.

\footnotesize

|Trophic level                                   | Present-natural - Current        | Current - Rewilding              | Present-natural - Rewilding    |
|:-----------------------------------------------|:---------------------------------|:---------------------------------|:-------------------------------|
|                                                | **Protected areas**              |                                  |                                |
|Megacarnivores ($\geq 100 kg$)                  |  1.24$^{0.00}_{very \, large}$   |  -0.60$^{0.00}_{medium}$         |  0.64$^{0.00}_{medium}$        |
|Megaherbivores ($\geq 1,000 kg$)                |  1.79$^{0.00}_{very \, large}$   |  -0.61$^{0.00}_{medium}$         |  1.18$^{0.00}_{large}$         |
|Large carnivores ($\geq 45 kg, \, < 100 kg$)    |  0.35$^{0.00}_{small}$           |  -0.13$^{0.06}_{very \, small}$  |  0.22$^{0.00}_{small}$         |
|Large herbivores ($\geq 500 kg, \, < 1,000 kg$) |  0.82$^{0.00}_{large}$           |  -0.33$^{0.00}_{small}$          |  0.49$^{0.00}_{small}$         |
|Small carnivores ($< 45 kg$)                    |  0.06$^{0.01}_{very \, small}$   |  -0.04$^{0.19}_{very \, small}$  |  0.02$^{0.79}_{very \, small}$ |
|Small herbivores ($< 500 kg$)                   |  0.03$^{0.40}_{very \, small}$   |  -0.01$^{1.00}_{very \, small}$  |  0.02$^{1.00}_{very \, small}$ |
|                                                | **Random areas**                 |                                  |                                |
|Megacarnivores ($\geq 100 kg$)                  |  1.89$^{0.00}_{very \, large}$   |  -1.21$^{0.00}_{very \, large}$  |  0.67$^{0.00}_{medium}$        |
|Megaherbivores ($\geq 1,000 kg$)                |  2.49$^{0.00}_{huge}$            |  -1.31$^{0.00}_{very \, large}$  |  1.19$^{0.00}_{large}$         |
|Large carnivores ($\geq 45 kg, \, < 100 kg$)    |  0.68$^{0.00}_{medium}$          |  -0.48$^{0.00}_{small}$          |  0.20$^{0.00}_{small}$         |
|Large herbivores ($\geq 500 kg, \, < 1,000 kg$) |  1.10$^{0.00}_{large}$           |  -0.59$^{0.00}_{medium}$         |  0.50$^{0.00}_{medium}$        |
|Small carnivores ($< 45 kg$)                    |  0.09$^{0.00}_{very \, small}$   |  -0.07$^{0.01}_{very \, small}$  |  0.02$^{0.92}_{very \, small}$ |
|Small herbivores ($< 500 kg$)                   |  0.04$^{0.06}_{very \, small}$   |  -0.02$^{0.57}_{very \, small}$  |  0.02$^{0.91}_{very \, small}$ |

\normalsize

<!-- All trophic levels, except small herbivores and small carnivores, have been heavily depleted (Table 1). Compared to protected areas, the effect sizes for large random areas were equal or greater. For the rewilding scenario, species richness in each trophic level increased from current conditions but not to present-natural levels. The recovery was larger in magnitude compared to protected areas. Notably, rewilding deficit, i.e. the difference between rewilding and present-natural trophic level richness, was comparable between random and protected areas (Table 1), showing a similar relative restoration potential of trophic rewilding. The effect of late-Quaternary extinctions and extirpations was generally higher in random areas than in protected areas. The restoration potential of rewilding was also higher in the random areas, as the number of species per trophic level increased in similar proportions in protected and random areas. -->

![Model estimates of the number of species per trophic level for protected areas >= 5,000 km^2 (left) and for the counter-factual areas >= 5,000 km^2 (right) under the three scenario examined: PN, present-natural (green); CU, current (blue); RW, rewilding (red). Circles represent estimates and lines the 95\% confidence interval. Human-driven extinctions and extirpations decreased the number of species decreased in all trophic levels except small carnivores and small herbivores. Under the rewilding scenario, the number of species in each trophic level increased, but not to present-natural levels. **add figurines; background grids; once this is finalized I will add size to facet headers.**](Figures/result1.png){ width=75% }

The number of interactions among trophic levels decreased between present-natural and current conditions in protected areas (Fig. 3). All interactions that involved megacarnivores were significantly reduced under current conditions compared to the present-natural, with very large effect sizes (Table 2). Predator-prey interactions maintained by large carnivores also significantly decreased between present-natural and current conditions, with large declines in the number of predator-prey interactions between large herbivores and large carnivores and small reductions in the number of interactions between small mammals and large carnivores. Under the rewilding scenario, the number of interactions between impacted trophic levels increased with small to large effect sizes; only interactions between large herbivore and large carnivores were not significantly different from current conditions. In the counter-factual areas >= 5,000 km^2 we observed similar but more pronounced patterns than in protected areas (figure 2).

Rewilding credit did not significantly balance current debt and trophic interactions were not completely restored to present-natural levels. The number of large herbivores-large carnivores interactions and all trophic links involving megacarnivores did not increased to present-natural levels, with medium to large effect sizes (Table 2). These patterns were qualitatively similar between protected and random areas, with higher extinctions debt and rewilding credit in random areas. Rewilding deficit was comparable between protected and random areas.

![Model estimates of the number of predator-prey interactions between trophic levels for protected (left) and counter-factual (right) areas >= 5,000 km^2 under the three scenario: PN, present-natural (green); CU, current (blue); RW, rewilding (red). Circles represent estimates and lines the 95\% confidence intervals. The number of trophic interactions promoted by megacarnivores and large carnivores in current food webs ware significantly lower than in present-natural. The number of interactions significantly increased under the rewilding scenario. Rewilding food webs were not completely restored, however, to present-natural levels. **add figurines; background grids; once this is finalized I will add size to facet headers.**](Figures/result2.png){ width=75% }

Table 2: Differences between regression coefficients estimates from generalised linear mixed models for the number of predator-prey interactions between trophic levels among scenarios: PN, present-natural; CU, current; RW, rewilding. The differences were obtained by performing multiple pair-wise contrasts accounting for variation across biogeographic realms and food webs. Superscripts show the p-value of the contrasts adjusted with Bonferroni correction and subscripts show the magnitude of the effect size of the change using Cohen's *d*: very small, *d* < 0.20; small *d* = 0.20-0.49; medium *d* = 0.50-0.79; large, *d* = 0.80-1.20; very large, *d* = 1.20-2.00; and huge, *d* >= 2.00.

\footnotesize

|Prey                        |Predator             | Present-natural - Current        | Current - Rewilding              | Present-natural - Rewilding    |
|:---------------------------|:--------------------|:---------------------------------|:---------------------------------|:-------------------------------|
|                            |                     | **Protected areas**              |                                  |                                |
|Large carnivores            |Megacarnivores       |  1.30$^{0.00}_{very \, large}$   |  -0.73$^{0.00}_{medium}$         |  0.56$^{0.00}_{medium}$         |
|Large herbivores            |Megacarnivores       |  1.92$^{0.00}_{very \, large}$   |  -0.74$^{0.00}_{medium}$         |  1.19$^{0.00}_{large}$          |
|Small carnivores            |Megacarnivores       |  1.45$^{0.00}_{very \, large}$   |  -0.84$^{0.00}_{large}$          |  0.62$^{0.00}_{medium}$         |
|Small herbivores            |Megacarnivores       |  1.31$^{0.00}_{very \, large}$   |  -0.74$^{0.00}_{medium}$         |  0.57$^{0.00}_{medium}$         |
|Large herbivores            |Large carnivores     |  0.93$^{0.00}_{large}$           |  -0.19$^{0.17}_{very \, small}$  |  0.74$^{0.00}_{medium}$         |
|Small carnivores            |Large carnivores     |  0.41$^{0.00}_{small}$           |  -0.27$^{0.00}_{small}$          |  0.14$^{0.07}_{very \, small}$  |
|Small herbivores            |Large carnivores     |  0.26$^{0.00}_{small}$           |  -0.14$^{0.04}_{very \, small}$  |  0.12$^{0.09}_{very \, small}$  |
|Small herbivores            |Small carnivores     |  0.08$^{0.37}_{very \, small}$   |  -0.06$^{0.67}_{very \, small}$  |  0.02$^{1.00}_{very \, small}$  |
|                            |                     | **Random areas**                 |                                  |                                |
|Large carnivores            |Megacarnivores       |  2.26$^{0.00}_{huge}$            |  -1.70$^{0.00}_{very \, large}$  |  0.56$^{0.00}_{medium}$        |
|Large herbivores            |Megacarnivores       |  2.67$^{0.00}_{huge}$            |  -1.60$^{0.00}_{very \, large}$  |  1.08$^{0.00}_{large}$         |
|Small carnivores            |Megacarnivores       |  2.05$^{0.00}_{huge}$            |  -1.42$^{0.00}_{very \, large}$  |  0.63$^{0.00}_{medium}$        |
|Small herbivores            |Megacarnivores       |  1.99$^{0.00}_{very \, large}$   |  -1.40$^{0.00}_{very \, large}$  |  0.59$^{0.00}_{medium}$        |
|Large herbivores            |Large carnivores     |  1.34$^{0.00}_{very \, large}$   |  -0.72$^{0.00}_{medium}$         |  0.63$^{0.00}_{medium}$        |
|Small carnivores            |Large carnivores     |  0.89$^{0.00}_{large}$           |  -0.80$^{0.00}_{large}$          |  0.09$^{0.56}_{very \, small}$ |
|Small herbivores            |Large carnivores     |  0.64$^{0.00}_{medium}$          |  -0.55$^{0.00}_{medium}$         |  0.09$^{0.51}_{very \, small}$ |
|Small herbivores            |Small carnivores     |  0.14$^{0.05}_{very \, small}$   |  -0.12$^{0.15}_{very \, small}$  |  0.03$^{1.00}_{very \, small}$ |

\normalsize

# Discussion
During the last 50,000 years, the expansion of modern humans has been associated with species' extinctions and extirpations, especially of large-bodied species [@martin1984prehistoric; @smith2018body]. These extinctions degraded ecological networks by removing predator-prey interactions that controlled ecosystems' trophic structure [@malhi2016megafauna]. A recently proposed approach to restore ecosystems and rewire ecological networks is trophic rewilding, the (re)introduction of species to promote biodiverse, self-sustaining ecosystems [@svenning2016science]. Empirical studies at local scales suggest rewilding can be an effective strategy for biodiversity conservation and ecosystem restoration, e.g. by maintaining semi-open landscapes and re-establishing lost ecological interactions [@riesch2019grazing; @garrido2019experimental; @genes2019effects]. However, the potential of rewilding to restore ecological networks to present-natural levels at global scale has not been investigated so far. Our study use macroecological approaches at global scales with deep-time perspectives to investigate the restoration potential of trophic rewilding. Overall, our results show that rewilding can rewire food webs globally, but not completely restore trophic complexity under a conservative approach that minimises ecological risks and human-wildlife conflict.

We found that trophic levels of larger body-sized mammals were, not surprisingly [@malhi2016megafauna; @smith2018body], the most affected by human pressure. The number of megacarnivores and megaherbivores significantly reduced due to extinctions with very large or huge effect sizes. The number of large carnivores and large herbivores also significantly decreased with, however, smaller effect sizes. Importantly, large carnivores declined in the random areas with higher effect sizes than in the protected areas, suggesting that human impact on trophic structure has been more severe at global scale than what observed focusing only on protected areas. As a consequence of these declines, trophic interactions maintained by megacarnivores and large carnivores were lost, degrading ecosystems' top-down control and trophic structure. Trophic complexity is important for self-sustaining biodiverse ecosystems [@perino2019rewilding], thus the removal of large-bodied mammals and the subsequent degradation of food webs complexity and community trophic structure likely jeopardises ecosystem stability and resilience [@estes2011trophic].

Our study shows that trophic level richness and interactions debts due to extinctions can partly be balanced by rewilding credit. The reintroduction of species into their present-natural ranges together with replacement of globally extinct species with functional analogues increased the number of species in affected trophic levels, showing intermediate to high potential for recovery. Although trophic level richness and complexity of trophic interactions increased with rewilding, these were still lower than present-natural levels. The complete restoration of food webs to pre-human conditions cannot be achieved under the conservative rewilding scenario examined, with medium to high levels of rewilding deficit. Importantly, as replacement of extinct species was phylogenetically constrained, a rewilding approach that focuses only on functional traits (e.g. mass, diet, and habitat) may restore food webs to present-natural conditions more effectively. **These are all new findings; not sure which citation to use**

We found that extinction debt and rewilding credit are higher in the random areas than in the protected areas with strict IUCN management (Ia, Ib, and II). Human land-use, e.g. agriculture, farmland, and urban areas, is concentrated in highly productive areas that has higher biodiversity and species richness [@luck2007relationships; @venter2018bias] and the network of protected areas has limited coverage for current mammalian biodiversity hotspots [@daru2019spatial]. As more severe losses happened in the random, geographically unbiased areas, rewilding credit and restoration potential are also higher compared to protected areas. Notably though, rewilding deficit magnitudes are comparable between protected and random areas, suggesting rewilding can rewire food webs to similar present-natural levels. Taken together, these results highlight the potential of rewilding to restore trophic interactions at global scale.

While we assessed the ecological consequences of adopting a conservative rewilding strategy, the outcome of rewilding depends also on societal and political factors. Society will play an important role in rewilding implementation and success, especially where rewilding might intensify human-wildlife conflicts **happy to say coexistence, I just don't find the correct verb**  [@perino2019rewilding]. For example, rewilding can cause economic losses to local stakeholders via predation on livestock or damages to crops and pastures. People not directly damaged by wildlife can also negatively perceive rewilding projects depending on how they are implemented [@theunissen2019oostvaardersplassen]. Human-wildlife conflict can, however, be mitigated by the adoption of compensation schemes by governmental agencies [@navarro2015rewilding]. For instance, aligning scientific, managers, and people's conception of nature with rewilding goals is a first step towards successful implementations of rewilding initiatives [@theunissen2019oostvaardersplassen] and identifying benefits and costs of wildlife in a socio-ecological framework can highlight possible actions to remedy unwanted outcomes of rewilding [@ceausu2019governing]. Importantly, new opportunities for implementing rewilding are occurring at local to regional scales, as recently shown by the return of wildlife in abandoned agricultural areas in Europe [@ceausu2015mapping; @chapron2014recovery]. Because human intervention at these large scales will likely be unfeasible because of limited funding and resources, trophic rewilding provides an alternative, feasible approach for ecosystem conservation and restoration. If and how rewilding is adopted will determine whether trophic complexity is restored in large areas where traditional conservation and restoration strategies are unfeasible.
<!-- Importantly, previously inhabited areas are being abandoned in Western countries and traditional conservation and restoration strategies may be ineffective or too expensive to be applied at these large spatial scales **(ref here?)**. Rewilding, however, can provide an alternative approach that does not require the amount of resources needed for traditional ecosystem conservation and restoration. -->
<!--  For instance, re-expansion of species is already happening in abandoned European landscapes [@chapron2014recovery; @deinet2017wildlife] and trophic rewilding can be built around the comebacks of large mammals to maximize the long-term effect of biodiversity conservation and restoration. -->
<!-- Also, the goals of traditional ecosystem conservation and restoration strategies and rewilding may not be so different as perceived [@van2019reconciling], and looking for a common ground and mutual understanding among scientific community, practitioners, and local communities will determine whether rewilding will be successful [@anderson2019introducing]. -->

In conclusion, our study shows human-driven extinctions severely degraded trophic complexity worldwide and that a conservative rewilding strategy can partly, but not completely, restore trophic structure of ecosystems. To rewire food webs to pre-human conditions, rewilding needs to be taken with a bolder approach than the conservative scenario examined here. For instance, by selecting rewilding replacements based only on species' functional traits rather than phylogenetic relationships could increase the number of extinct species replaced and the restoration potential of rewilding to rewire food webs. Rewilding will probably be a controversial topic for long time and its implementation needs further improvements to secure the long-term restoration goals [@root2018rewilding]. This does not mean however that rewilding should be ostracised as a failing or unnecessary restoration strategy, but rather that policy makers, societal agencies, managers, and ecologists need to discuss and improve why and how rewilding is implemented. Overall, our findings show that a conservative rewilding strategy is a good starting point to restore ecosystems' trophic structure, but that rewilding cannot be so conservative and its restrictions need to be relaxed if the long-term goal is to achieve self-sustaining biodiverse ecosystems.

# Acknowledgment
This work is a contribution to the Carlsberg Foundation Semper Ardens project MegaPast2Future (grant CF16\-0005 to JCS). JCS also considers this work a contribution to his VILLUM FONDEN Investigator project 'Biodiversity Dynamics in a Changing World' (grant 16549). We thank members of the MegaPast2Future group for discussions that improved the manuscript.

# Data accessibility
All data used was open access. Predator-prey interactions were from the ECOWeB and GLOBI databases [@cohen2010ecoweb; @poelen2014global], and from two published papers [@baskerville2011spatial; @de2011serengeti]. Body mass and range maps were from the PHYLACINE 1.2 database [@faurby2018phylacine]. We used climate data from the Worldclim 2.0 database [@fick2017worldclim], elevation data from the EarthEnv-DEM90 digital elevation model [@robinson2014earthenv], and the biogeographic realms shapefile from the WWF [@olson2002global].

# Author contribution
EB conceived and developed the study, performed analyses, and drafted the manuscript. SJ and JCS conceived and developed the study, interpreted the results, and helped revise the manuscript.

# Competing interests
We have no competing interests.

# References
